---

- name: 'Ensure config directory exist.'
  file:
    path: "{{ promtail_config_dir }}"
    state: directory
  become: yes

- name: 'Download and unarchive promtail with version {{ promtail_version }}.'
  unarchive:
    src: "https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/promtail-linux-amd64.zip"
    dest: "/usr/local/bin"
    remote_src: yes
    creates: '/usr/local/bin/promtail-linux-amd64'
  become: yes

- name: 'Create symlink.'
  file:
    src: "/usr/local/bin/promtail-linux-amd64"
    dest: "{{ promtail_executable }}"
    state: link
  become: yes
  notify:
    - restart_promtail

- name: 'Copy systemd service file.'
  template: 
    src: promtail.service.j2 
    dest: /etc/systemd/system/promtail.service
  become: yes
  register: systemd

- name: 'Systemd daemon reload'
  systemd:
    daemon_reload: yes
  become: yes
  when: systemd.changed

- name: 'Copy promtail config file.'
  template: 
    src: config.yml.j2 
    dest: '{{ promtail_config_dir }}/config.yml'
  become: yes
  notify:
    - restart_promtail
